/**
 * Article detail sheet/modal for Today page
 *
 * Shows headline, source, why it matters, snippet, and actions:
 * - Read on source (external link)
 * - Bookmark toggle
 */

import { Sheet, SheetContent, SheetDescription, SheetTitle } from "@/components/ui/sheet"
import {
  SHEET_TOKENS,
  SheetHeaderBlock,
  SheetSection,
  SheetSectionCard,
  SheetSnippet,
  SheetActions,
  SheetIconButton,
} from "@/components/ui/sheet-primitives"
import { Bookmark } from "lucide-react"
import { toast } from "sonner"
import { Timestamp } from "firebase/firestore"
import { useIsBookmarked, useToggleBookmark } from "@/lib/hooks"
import { useAuth } from "@/lib/auth-context"
import type { TopStoryWithArticle } from "@/lib/hooks/use-today-brief"
import type { Article } from "@/types/firestore"
import { hapticLight } from "@/lib/haptics"

interface ArticleSheetProps {
  story: TopStoryWithArticle | null
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function ArticleSheet({ story, open, onOpenChange }: ArticleSheetProps) {
  const { isAuthenticated } = useAuth()
  const { data: isBookmarked } = useIsBookmarked(story?.article?.id)
  const toggleBookmark = useToggleBookmark()

  // Null safety: don't render if story or article is missing
  if (!story || !story.article) return null

  // Destructure for cleaner access (article is guaranteed non-null here)
  const { article } = story

  const handleOpenArticle = () => {
    hapticLight()
    window.open(article.url, "_blank", "noopener,noreferrer")
  }

  const handleBookmark = () => {
    if (!isAuthenticated) {
      toast.error("Sign in to bookmark articles")
      return
    }
    hapticLight()

    // Create a minimal Article object for bookmarking
    // The bookmark only stores essential fields anyway
    const minimalArticle: Article = {
      id: article.id,
      sourceId: article.sourceId ?? "",
      sourceName: article.sourceName,
      title: article.title,
      snippet: article.snippet,
      url: article.url,
      canonicalUrl: article.url,
      guid: null,
      imageUrl: article.imageUrl,
      categories: [],
      publishedAt: Timestamp.fromDate(new Date(article.publishedAt)),
      ingestedAt: Timestamp.now(),
      relevanceScore: 1,
      isRelevant: true,
      ai: null,
    }

    toggleBookmark.mutate(
      { article: minimalArticle, isCurrentlyBookmarked: !!isBookmarked },
      {
        onSuccess: ({ bookmarked }) => {
          toast.success(bookmarked ? "Article saved" : "Bookmark removed")
        },
        onError: () => {
          toast.error("Failed to update bookmark")
        },
      }
    )
  }

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent
        side="bottom"
        hideCloseButton
        className={SHEET_TOKENS.containerClass}
      >
        {/* Drag indicator */}
        <div className={SHEET_TOKENS.dragIndicatorClass} />

        {/* Accessibility: Visually hidden title for screen readers */}
        <SheetTitle className="sr-only">{story.headline}</SheetTitle>
        <SheetDescription className="sr-only">
          Article details from {article.sourceName}
        </SheetDescription>

        {/* Header */}
        <SheetHeaderBlock
          source={article.sourceName}
          title={story.headline}
        />

        {/* Image */}
        {article.imageUrl && (
          <div className={SHEET_TOKENS.imageClass}>
            <img
              src={article.imageUrl}
              alt=""
              className="h-full w-full object-cover"
            />
          </div>
        )}

        {/* Why It Matters Card */}
        <SheetSectionCard
          className={SHEET_TOKENS.sectionMargin}
          footer={
            <p className="text-[11px] text-[var(--color-text-tertiary)]">
              Summary generated by AI. Read original source for full article.
            </p>
          }
        >
          <SheetSection label="Why It Matters">
            {story.whyItMatters}
          </SheetSection>
        </SheetSectionCard>

        {/* Snippet */}
        {article.snippet && (
          <SheetSnippet>{article.snippet}</SheetSnippet>
        )}

        {/* Actions */}
        <SheetActions
          onReadArticle={handleOpenArticle}
          secondaryButton={
            <SheetIconButton
              onClick={handleBookmark}
              disabled={toggleBookmark.isPending}
              loading={toggleBookmark.isPending}
              aria-label={isBookmarked ? "Remove bookmark" : "Bookmark article"}
            >
              <Bookmark
                className="h-[20px] w-[20px]"
                fill={isBookmarked ? "currentColor" : "none"}
              />
            </SheetIconButton>
          }
        />
      </SheetContent>
    </Sheet>
  )
}

